# please configure 根据实际情况选择操作系统镜像
FROM debian:12

WORKDIR /tmp
COPY ./version.info ./
COPY ./ascend_install.info ./
COPY ./Ascend-cann-toolkit_*.run ./
COPY ./Ascend-cann-kernels-*.run ./

# 1.配置证书
RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# 2.配置Debian源
RUN echo "deb https://mirrors.huaweicloud.com/debian/ bookworm main contrib non-free" > ./sources.list && \
    echo "deb-src https://mirrors.huaweicloud.com/debian/ bookworm main contrib non-free" >> ./sources.list && \
    echo "deb https://mirrors.huaweicloud.com/debian-security/ bookworm-security main contrib non-free" >> ./sources.list && \
    echo "deb-src https://mirrors.huaweicloud.com/debian-security/ bookworm-security main contrib non-free" >> ./sources.list && \
    echo "deb https://mirrors.huaweicloud.com/debian/ bookworm-updates main contrib non-free" >> ./sources.list && \
    echo "deb-src https://mirrors.huaweicloud.com/debian/ bookworm-updates main contrib non-free" >> ./sources.list

# 3.安装编译环境
RUN mv /etc/apt/sources.list.d/debian.sources /etc/apt/sources.list.d/debian.sources.bak && \
    cp -f ./sources.list /etc/apt/ && \
    apt-get update && \
    apt-get -y install net-tools make wget zlib1g-dev bzip2 libbz2-dev libssl-dev libncurses5-dev libncursesw5-dev openssh-client \
    openssh-server libsqlite3-dev libopenmpi-dev libreadline-dev tk-dev libgdbm-dev libdb-dev libpcap-dev liblzma-dev  \
    libffi-dev libhdf5-dev patch pciutils lcov vim dos2unix g++ automake libtool autoconf m4 perl git e2fsprogs && \
    apt-get clean && \
    rm -rf /var/cache/apt/
# 注：openssh-server为双机训练样例需要，仅单机训练时可去掉

# 编译安装 GCC 11.2.0
RUN wget https://mirrors.huaweicloud.com/gnu/gcc/gcc-11.2.0/gcc-11.2.0.tar.gz && \
    tar -zxvf gcc-11.2.0.tar.gz && \
    cd gcc-11.2.0 && \
    wget https://mirrors.huaweicloud.com/gnu/gmp/gmp-6.1.0.tar.bz2 && \
    wget https://mirrors.huaweicloud.com/gnu/mpfr/mpfr-3.1.6.tar.bz2 && \
    wget https://mirrors.huaweicloud.com/gnu/mpc/mpc-1.0.3.tar.gz && \
    wget https://gcc.gnu.org/pub/gcc/infrastructure/isl-0.18.tar.bz2 && \
    sed -i "246s/tar -xf \"\${ar}\"/tar --no-same-owner -xf \"\${ar}\"/" contrib/download_prerequisites && \
    ./contrib/download_prerequisites && \
    ./configure --enable-languages=c,c++ --disable-multilib --with-system-zlib --prefix=/usr/local/gcc11.2.0 && \
    make -j $(nproc) && make install && \
    find /tmp/gcc-11.2.0/ -name libstdc++.so.6.0.29 -exec cp {} /lib64/ \; && \
    rm -rf /tmp/gcc-11.2.0* && \
    update-alternatives --install /usr/bin/gcc gcc /usr/local/gcc11.2.0/bin/gcc 100 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/local/gcc11.2.0/bin/g++ 100 && \
    update-alternatives --set gcc /usr/local/gcc11.2.0/bin/gcc && \
    update-alternatives --set g++ /usr/local/gcc11.2.0/bin/g++


# 4.安装cmake-3.22.6
RUN wget https://cmake.org/files/v3.22/cmake-3.22.6.tar.gz && \
    . /etc/profile && gcc -v && tar -zxf /tmp/cmake-3.22.6.tar.gz && \
    cd cmake-3.22.6 && \
    ./bootstrap && make -j $(nproc) && make install && \
    rm -rf /tmp/cmake-3.22.6*

# 5.安装python3.11.0
RUN wget https://mirrors.huaweicloud.com/python/3.11.0/Python-3.11.0.tar.xz && \
    . /etc/profile && gcc -v && tar -xvf /tmp/Python-3.11.0.tar.xz && \
    cd Python-3.11.0 && \
    mkdir -p build && cd build && \
    ../configure --enable-shared --prefix=/usr/local/python3.11.0 && \
    make -j $(nproc) && make install && \
    rm -rf /tmp/Python-3.11.0* && \
    ldconfig

ENV PATH=$PATH:/usr/local/python3.11.0/bin \
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/python3.11.0/lib

RUN ln -s /usr/local/python3.11.0/bin/python3 /usr/bin/python && \
    ln -s /usr/local/python3.11.0/bin/pip3 /usr/bin/pip

# 配置python源
RUN mkdir ~/.pip && touch ~/.pip/pip.conf && \
    echo "[global]" > ~/.pip/pip.conf && \
    echo "trusted-host=mirrors.aliyun.com" >> ~/.pip/pip.conf && \
    echo "index-url=https://mirrors.aliyun.com/pypi/simple/" >> ~/.pip/pip.conf && \
    echo "timeout=200" >> ~/.pip/pip.conf

# 6.安装python包
RUN wget https://download.pytorch.org/whl/cpu/torch-2.6.0%2Bcpu-cp311-cp311-linux_x86_64.whl && \
    wget https://download.pytorch.org/whl/cpu/fbgemm_gpu-1.1.0%2Bcpu-cp311-cp311-manylinux2014_x86_64.whl

RUN pip3 install -U pip && \
    pip3 install numpy==1.25.0 && \
    pip3 install wheel && \
    pip3 install decorator && \
    pip3 install sympy==1.13.3 && \
    pip3 install cffi==1.17.1 && \
    pip3 install expecttest && \
    pip3 install pybind11 && \
    pip3 install pyyaml && \
    pip3 install psutil && \
    pip3 install pathlib2 && \
    pip3 install pandas==2.2.3 && \
    pip3 install grpcio && \
    pip3 install grpcio-tools==1.67.0 && \
    pip3 install protobuf==5.28.2 && \
    pip3 install scipy==1.14.1 && \
    pip3 install requests && \
    pip3 install scikit-learn && \
    pip3 install easydict && \
    pip3 install attrs && \
    pip3 install pytest && \
    pip3 install pytest-cov && \
    pip3 install pytest-html && \
    pip3 install Cython && \
    pip3 install absl-py && \
    pip3 install gin-config && \
    pip3 install torch-2.6.0+cpu-*.whl && \
    pip3 install fbgemm_gpu-1.1.0+cpu-*.whl && \
    pip3 install torch-npu==2.6.0 && \
    pip3 install tensorboard==2.18.0 && \
    pip3 install black && \
    pip3 install cmake && \
    pip3 install hypothesis==6.70.1 && \
    pip3 install iopath && \
    pip3 install pyre-extensions && \
    pip3 install scikit-build && \
    pip3 install torchmetrics==1.0.3 && \
    pip3 install torchx && \
    pip3 install tqdm && \
    pip3 install usort && \
    pip3 install parameterized && \
    rm -rf /root/.cache/pip


# 7.设置驱动路径环境变量
ARG ASCEND_BASE=/usr/local/Ascend
ENV LD_LIBRARY_PATH=$ASCEND_BASE/driver/lib64:$ASCEND_BASE/driver/lib64/common:$ASCEND_BASE/driver/lib64/driver:$LD_LIBRARY_PATH

# 8.安装ascend-toolkit与kernels算子包
# 9.CANN相关参数
ARG TOOLKIT_PKG=Ascend-cann-toolkit*.run
ARG KERNEL_PKG=Ascend-cann-kernels*.run
# 10.删除旧的CANN
RUN rm -rf $ASCEND_BASE/ascend-toolkit

RUN umask 0027 && \
   chmod +x $TOOLKIT_PKG && \
   bash $TOOLKIT_PKG --quiet --install --install-path=$ASCEND_BASE && \
   . $ASCEND_BASE/ascend-toolkit/set_env.sh && \
   chmod +x $KERNEL_PKG && \
   bash $KERNEL_PKG --quiet --install && \
   rm -rf /root/.cache/pip && \
   rm -f $TOOLKIT_PKG && rm -f $KERNEL_PKG

# 11.清理临时目录
RUN rm -rf ./*