import re
import os
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.shared import qn
from docx.oxml import OxmlElement
from docx.shared import RGBColor

def add_title(document, text):
    """添加标题"""
    heading = document.add_heading(level=1)
    run = heading.add_run(text)
    run.font.size = Pt(16)
    run.font.bold = True
    run.font.color.rgb = RGBColor(0x2E, 0x75, 0xB6)  # 蓝色字体

def add_subtitle(document, text):
    """添加副标题"""
    heading = document.add_heading(level=2)
    run = heading.add_run(text)
    run.font.size = Pt(14)
    run.font.bold = True
    run.font.color.rgb = RGBColor(0x00, 0x00, 0x00)  # 黑色字体

def add_section_title(document, text):
    """添加章节标题"""
    heading = document.add_heading(level=3)
    run = heading.add_run(text)
    run.font.size = Pt(12)
    run.font.bold = True

def add_paragraph_with_format(document, text):
    """添加格式化段落"""
    if not text.strip():
        document.add_paragraph()
        return
        
    paragraph = document.add_paragraph()
    run = paragraph.add_run(text)
    run.font.size = Pt(11)
    return paragraph

def add_code_block(document, code_text, language=""):
    """添加带格式的代码块"""
    # 添加语言标识
    if language:
        paragraph = document.add_paragraph()
        run = paragraph.add_run(f"[{language} 代码]")
        run.font.size = Pt(9)
        run.font.italic = True
        run.font.color.rgb = RGBColor(0x6C, 0x75, 0x7D)  # 灰色字体
    
    # 创建代码块段落
    code_paragraph = document.add_paragraph()
    code_paragraph.style = 'Normal'
    
    # 设置代码字体和样式
    run = code_paragraph.add_run(code_text)
    run.font.name = 'Consolas'  # 使用等宽字体
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0xD6, 0x33, 0x84)  # 粉红色字体
    
    # 设置段落格式
    code_paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
    code_paragraph.paragraph_format.left_indent = Inches(0.3)
    code_paragraph.paragraph_format.right_indent = Inches(0.3)
    code_paragraph.paragraph_format.space_before = Pt(6)
    code_paragraph.paragraph_format.space_after = Pt(6)
    
    # 添加浅灰色背景（通过添加底纹实现）
    # 注意：python-docx 不直接支持背景色，但可以通过底层XML实现
    shd = OxmlElement('w:shd')
    shd.set(qn('w:fill'), "F8F9FA")  # 浅灰色背景
    code_paragraph.paragraph_format.element.get_or_add_pPr().append(shd)

def add_mermaid_placeholder(document, diagram_number):
    """添加Mermaid图表占位符"""
    # 添加提示文本
    paragraph = document.add_paragraph()
    run = paragraph.add_run(f"[Mermaid图表 {diagram_number} 应在此处显示]")
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(0x19, 0x87, 0x54)  # 绿色字体
    run.font.bold = True
    
    # 添加说明
    paragraph = document.add_paragraph()
    run = paragraph.add_run("您可以使用以下方式查看此图表:")
    run.font.size = Pt(9)
    run.font.italic = True
    
    # 添加操作步骤
    steps = [
        "1. 打开 mermaid_sources/diagram_{}.mmd 文件查看Mermaid源码".format(diagram_number),
        "2. 将代码复制到 https://mermaid.live/ 在线编辑器中查看",
        "3. 或在支持的环境中使用 mermaid-cli 工具生成SVG/PNG图像"
    ]
    
    for step in steps:
        paragraph = document.add_paragraph(step, style='List Bullet')
        paragraph.paragraph_format.left_indent = Inches(0.5)
        paragraph.paragraph_format.space_before = Pt(0)
        paragraph.paragraph_format.space_after = Pt(0)
        run = paragraph.runs[0]
        run.font.size = Pt(9)

def convert_md_to_docx(md_file_path, docx_file_path):
    """将Markdown文件转换为格式化的Word文档"""
    # 创建文档
    document = Document()
    
    # 设置文档属性
    section = document.sections[0]
    section.page_height = Inches(11)
    section.page_width = Inches(8.5)
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)
    
    # 添加标题
    document.core_properties.title = "Feature Filter 完整设计文档"
    document.core_properties.author = "Generated by Python Script"
    
    # 读取Markdown文件
    with open(md_file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 分割内容为行
    lines = content.split('\n')
    
    # 初始化变量
    diagram_count = 0
    in_code_block = False
    in_mermaid_block = False
    code_block_content = ""
    code_language = ""
    
    # 处理每一行
    i = 0
    while i < len(lines):
        line = lines[i]
        
        # 检查是否是标题
        if line.startswith('# ') and not in_code_block:
            add_title(document, line[2:])
        elif line.startswith('## ') and not in_code_block:
            add_subtitle(document, line[3:])
        elif line.startswith('### ') and not in_code_block:
            add_section_title(document, line[4:])
        # 检查是否是代码块开始
        elif line.startswith('```') and not in_code_block:
            # 确定代码语言
            if line.startswith('```cpp'):
                code_language = "C++"
                in_code_block = True
                i += 1
                continue
            elif line.startswith('```python'):
                code_language = "Python"
                in_code_block = True
                i += 1
                continue
            elif line.startswith('```mermaid'):
                in_mermaid_block = True
                diagram_count += 1
                i += 1
                continue
            elif line.startswith('```'):
                code_language = "代码"
                in_code_block = True
                i += 1
                continue
        # 检查是否是代码块结束
        elif line.startswith('```') and (in_code_block or in_mermaid_block):
            if in_code_block:
                # 添加代码块到文档
                add_code_block(document, code_block_content, code_language)
                code_block_content = ""
                code_language = ""
                in_code_block = False
            elif in_mermaid_block:
                # 添加Mermaid图表占位符
                add_mermaid_placeholder(document, diagram_count)
                in_mermaid_block = False
            i += 1
            continue
        # 处理代码块内容
        elif in_code_block or in_mermaid_block:
            code_block_content += line + "\n"
        # 处理普通段落
        else:
            add_paragraph_with_format(document, line)
        
        i += 1
    
    # 保存文档
    document.save(docx_file_path)
    print(f"文档已保存为 {docx_file_path}")

def main():
    md_file_path = "feature_filter_complete_design.md"
    docx_file_path = "beautiful_feature_filter_design.docx"
    
    convert_md_to_docx(md_file_path, docx_file_path)
    print("转换完成！")

if __name__ == "__main__":
    main()