[mxrec]
key_process = ["getBatchData", "getAndProcess"]
process_emb_info = ["getAndSendTensors"]
lookup_swap_addr = ["lookupAddrs"]
embedding_recv = ["EmbeddingRecv", "EmbeddingUpdate", "SendH2DEmb"]
