[project]
name = "mxrec_for_lingqu"
authors = [{ name = "HUAWEI Inc" }]
description = "MindX SDK Recommend for Lingqu 2.0"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = "==3.7.5"
license = { file = "LICENSE" }
classifiers = [
    "Private :: Do Not Upload",
    "Programming Language :: Python :: 3",
]

dynamic = ["version"]

[project.optional-dependencies]
test = ["pytest ==7.4.4", "pytest-cov ==4.1.0", "pytest-html ==4.1.1"]

[project.urls]
Homepage = "https://gitee.com/ascend/mxrec-for-lingqu2.0"

[tool.pyright]
reportGeneralTypeIssues = false
reportReturnType = false
reportArgumentType = false
reportAssignmentType = false
reportInvalidTypeForm = false
reportCallIssue = false
reportAttributeAccessIssue = false

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
